apiVersion: v2
name: aiven-operator
description: A Helm chart to deploy the aiven operator
type: application
version: v0.23.0
appVersion: v0.23.0
maintainers:
  - name: byashimov
    url: https://www.aiven.io
  - name: jeff-held-aiven
    url: https://www.aiven.io
  - name: rriski
    url: https://www.aiven.io
