apiVersion: v2
name: aiven-operator
description: A Helm chart to deploy the aiven operator
type: application
version: v0.10.1
appVersion: v0.10.0
maintainers:
  - name: mhoffm-aiven
    url: https://www.aiven.io
  - name: ivan-savciuc
    url: https://www.aiven.io
