---
# permissions for end users to view grafanas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: grafana-viewer-role

rules:
  - apiGroups: [aiven.io]
    resources: [grafanas]
    verbs: [get, list, watch]
  - apiGroups: [aiven.io]
    resources: [grafanas/status]
    verbs: [get]
