# permissions for end users to view kafkas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafka-viewer-role
rules:
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - kafkas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - kafkas/status
  verbs:
  - get
